# Generated by Django 4.0.3 on 2022-03-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_author_id_alter_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='books_img'),
        ),
    ]
