# Generated by Django 4.0.3 on 2022-04-02 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
